environment: development
random_seed: 20250927
paths:
  data_dir: data
  output_dir: output
  cache_dir: .cache
  logs_dir: logs
  metadata_dir: metadata
observability:
  quarantine_enabled: false
  quarantine_dir: metadata/quarantine
audit_mode:
  enabled: false
policies:
  policy_version: "0.1"
  level_thresholds:
    level_0:
      min_institutions: 1
      min_src_count: 1
      weight_formula: "1.0*inst_count + 0.3*log(1+src_count)"
    level_1:
      min_institutions: 1
      min_src_count: 1
      weight_formula: "1.0*inst_count + 0.3*log(1+src_count)"
    level_2:
      min_institutions: 2
      min_src_count: 1
      weight_formula: "1.0*inst_count + 0.3*log(1+src_count)"
    level_3:
      min_institutions: 2
      min_src_count: 3
      weight_formula: "1.0*inst_count + 0.3*log(1+src_count)"
  frequency_filtering:
    unknown_institution_placeholder: "placeholder::unknown"
    near_duplicate:
      enabled: true
      prefix_delimiters:
        - "::"
        - "#"
        - "@"
      strip_numeric_suffix: true
      min_prefix_length: 6
  label_policy:
    minimal_canonical_form:
      case: lower
      remove_punctuation: true
      fold_diacritics: true
      collapse_whitespace: true
      min_length: 2
      max_length: 64
      boilerplate_patterns:
        - "department of"
        - "school of"
        - "college of"
        - "program in"
    token_minimality_preference: prefer_shortest_unique
    punctuation_handling: strip_terminal
  single_token:
    max_tokens_per_level:
      0: 2
      1: 2
      2: 3
      3: 2
    forbidden_punctuation:
      - "-"
      - "_"
      - "."
      - "/"
      - ":"
    allowlist:
      - "computer vision"
      - "machine learning"
      - "natural language processing"
      - "artificial intelligence"
      - "data science"
    venue_names:
      - "neurips"
      - "neural information processing systems"
      - "icml"
      - "international conference on machine learning"
      - "cvpr"
      - "computer vision and pattern recognition"
      - "acl"
      - "association for computational linguistics"
      - "emnlp"
      - "kdd"
      - "siggraph"
      - "isca"
    venue_names_forbidden: true
    hyphenated_compounds_allowed: false
    prefer_rule_over_llm: true
  institution_policy:
    campus_vs_system: prefer-campus
    joint_center_handling: duplicate-under-both
    cross_listing_strategy: merge-with-stronger-parent
    canonical_mappings: {}
  web:
    allowed_domains:
      - ".edu"
      - ".org"
    disallowed_paths:
      - "/events"
      - "/news"
      - "/calendar"
    robots_txt_compliance: true
    dynamic_content: false
    pdf_processing_limit: 500
    ttl_cache_days: 14
    include_patterns: []
    robots_cache_ttl_hours: 12
    sitemap_discovery: true
    respect_crawl_delay: true
    firecrawl:
      concurrency: 6
      max_depth: 3
      max_pages: 300
      render_timeout_ms: 10000
      api_key_env_var: FIRECRAWL_API_KEY
      endpoint_url: null
      request_timeout_seconds: 20.0
      retry_attempts: 3
      user_agent: TaxonomyBot/1.0
    budgets:
      max_pages: 300
      max_depth: 3
      max_time_minutes: 30
      max_content_size_mb: 5
    content:
      language_allowlist:
        - en
      language_confidence_threshold: 0.6
      min_text_length: 120
      pdf_extraction_enabled: true
      pdf_size_limit_mb: 5
    cache:
      cache_directory: ".cache/web"
      ttl_days: 14
      cleanup_interval_hours: 12
      max_size_gb: null
    observability:
      metrics_enabled: true
      sampling_rate: 0.1
      example_snapshot_count: 5
  llm:
    temperature: 0.0
    nucleus_top_p: 1.0
    json_mode: true
    retry_attempts: 3
    retry_backoff_seconds: 2.0
    random_seed: 12345
    token_budget: 4096
    request_timeout_seconds: 30.0
    default_profile: standard
    profiles:
      standard:
        provider: openai
        model: gpt-4o-mini
    registry:
      file: prompts/registry.yaml
      templates_root: prompts
      schema_root: prompts
      hot_reload: false
    repair:
      quarantine_after_attempts: 3
    observability:
      metrics_enabled: true
      audit_logging: false
    cost_tracking:
      token_budget_per_hour: 20000
      enabled: false
  prompt_optimization:
    optimization_budget: heavy
    comprehensive_search: true
    deploy_immediately: true
    validation_ratio: 0.2
    random_seed: 20250927
    explore_all_few_shot_k: true
    explore_temperature_variants: true
    explore_constraint_variants: true
    default_few_shot_k: 2
    constraint_variant: baseline
    few_shot_k_options:
      - 0
      - 2
      - 4
    temperature_variants:
      - 0.0
      - 0.2
    constraint_variants:
      - baseline
      - guarded
      - compact
    json_validity_threshold: 0.995
    schema_adherence_threshold: 1.0
    strict_guardrail_enforcement: true
    min_trials_for_confidence: 30
    convergence_patience: 15
    backup_before_deployment: true
    validate_deployed_variant: true
    rollback_on_failure: true
    use_merge: true
    reflection_model: openai/gpt-4o
  disambiguation:
    min_parent_divergence: 0.3
    min_context_overlap_threshold: 0.2
    require_multiple_parents: true
    max_contexts_per_parent: 5
    context_window_size: 100
    min_token_frequency: 2
    llm_enabled: true
    max_contexts_for_prompt: 10
    gloss_max_words: 20
    min_evidence_strength: 0.6
    defer_ambiguous_threshold: 0.4
    allow_multi_parent_exceptions: false
    sample_splits_count: 5
    detailed_logging: false
  validation:
    rules:
      forbidden_patterns:
        - "neurips$"
        - "icml$"
        - "cvpr$"
        - "acl$"
        - "emnlp$"
        - "kdd$"
        - "siggraph$"
      required_vocabularies: {}
      venue_patterns:
        - "neurips"
        - "icml"
        - "cvpr"
        - "acl"
        - "emnlp"
        - "kdd"
        - "siggraph"
      structural_checks_enabled: true
    web:
      authoritative_domains:
        - "wikipedia.org"
        - "acm.org"
        - "ieee.org"
      snippet_max_length: 200
      min_snippet_matches: 1
      evidence_timeout_seconds: 10.0
    llm:
      entailment_enabled: true
      max_evidence_tokens: 1000
      confidence_threshold: 0.7
    aggregation:
      rule_weight: 1.0
      web_weight: 0.7
      llm_weight: 0.4
      hard_rule_failure_blocks: true
      tie_break_conservative: true
    evidence:
      max_snippets_per_concept: 3
      store_evidence_urls: true
      evidence_sampling_rate: 1.0
  observability:
    counter_registry_enabled: true
    evidence_sampling_rate: 0.1
    quarantine_logging_enabled: true
    max_evidence_samples_per_phase: 100
    deterministic_sampling_seed: 42
    performance_tracking_enabled: true
    audit_trail_generation: true
    manifest_checksum_validation: true
  hierarchy_assembly:
    enforce_acyclicity: true
    enforce_unique_paths: true
    allow_multi_parent_exceptions: []
    orphan_strategy: quarantine
    placeholder_parent_prefix: "placeholder::"
    strict_level_enforcement: true
    allow_level_shortcuts: false
    max_graph_size: 100000
    cycle_detection_method: topological_sort
    include_graph_stats: true
    include_invariant_proofs: true
  deduplication:
    thresholds:
      l0_l1: 0.93
      l2_l3: 0.9
    merge_policy: conservative
    prefix_length: 6
    phonetic_enabled: true
    phonetic_probe_threshold: 0.75
    acronym_blocking_enabled: true
    max_block_size: 1000
    jaro_winkler_weight: 1.0
    jaccard_weight: 1.0
    abbrev_score_weight: 1.2
    heuristic_suffixes:
      - systems
      - theory
      - engineering
    min_similarity_threshold: 0.85
    parent_context_strict: true
    cross_parent_merge_allowed: false
    max_comparisons_per_block: 10000
    enable_early_stopping: true
    sample_merge_count: 10
    detailed_logging: false
  raw_extraction:
    segment_on_headers: true
    segment_on_lists: true
    segment_on_tables: true
    preserve_list_structure: true
    min_chars: 12
    max_chars: 2000
    target_language: en
    language_confidence_threshold: 0.8
    intra_page_dedup_enabled: true
    similarity_threshold: 0.95
    similarity_method: jaccard_shingles
    remove_boilerplate: true
    boilerplate_patterns:
      - '© \d{4}'
      - "all rights reserved"
      - "privacy policy"
      - "terms of use"
      - "contact us"
      - 'home \| about \| contact'
    detect_sections: true
    section_header_patterns:
      - '^[A-Z][A-Z\s]{2,50}:?$'
      - '^#{1,6}\s+.+$'
      - '^\d+\.\s+[A-Z].+$'
    preserve_document_order: true
  level0_excel:
    excel_file: data/Faculty Extraction Report.xlsx
    sheets_to_process: []
    top_n_institutions: 25
    random_seed: 20230927
